# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('intake', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('numOfMed', models.IntegerField()),
                ('freqOfIntake', models.IntegerField()),
                ('alertVal', models.ManyToManyField(to='mainApp.Alert')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numLeft', models.IntegerField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='medicationVal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Medication'),
        ),
    ]
