# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
