# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20170204_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientEmail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='medicationVal',
        ),
        migrations.AddField(
            model_name='client',
            name='medicationVal',
            field=models.ManyToManyField(to='mainApp.Medication'),
        ),
    ]
